ekf_filter_node:
  ros__parameters:
    # 10Hz rf2o에 맞춰 EKF 주파수 조정
    frequency: 20.0  # rf2o의 2배
    sensor_timeout: 0.5  # ArUco가 간헐적이므로 타임아웃 증가
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    
    # 시간 관련 설정 - 중요!
    transform_time_offset: 0.1  # 작은 시간 오프셋 추가
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false
    
    # 예측 설정 - 초기 점프 방지
    predict_to_current_time: false  # false로 변경하여 과도한 예측 방지
    
    # -------------------------------
    # odom0: rf2o_laser_odometry (10Hz)
    # -------------------------------
    odom0: /odom_rf2o
    odom0_config: [true,  true,  false,    # x, y, z
                   false, false, true,     # roll, pitch, yaw
                   true,  true,  false,    # vx, vy, vz
                   false, false, true,     # vroll, vpitch, vyaw
                   false, false, false]    # ax, ay, az
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10  # 1초 분량의 데이터
    odom0_nodelay: false  # false로 변경
    odom0_pose_rejection_threshold: 2.0  # 더 엄격하게
    odom0_twist_rejection_threshold: 0.5
    
    # -------------------------------
    # pose0: ArUco (간헐적)
    # -------------------------------
    pose0: /aruco_yaw
    pose0_config: [false, false, false,    # x, y, z
                   false, false, true,     # roll, pitch, yaw
                   false, false, false,    # vx, vy, vz
                   false, false, false,    # vroll, vpitch, vyaw
                   false, false, false]    # ax, ay, az
    pose0_differential: false
    pose0_relative: false
    pose0_queue_size: 5
    pose0_nodelay: false
    pose0_rejection_threshold: 0.3
    
    # Mahalanobis distance threshold
    # 초기 점프 방지를 위한 설정
    mahalanobis_dr_threshold: 5.0
    mahalanobis_dm_threshold: 5.0
    
    # Smooth lagged data - 10Hz 데이터를 부드럽게
    smooth_lagged_data: true
    history_length: 0.2  # 200ms 히스토리
    
    # Process noise covariance (Q) - 10Hz에 맞춰 조정
    # 낮은 주파수를 고려하여 프로세스 노이즈 증가
    process_noise_covariance: [0.1,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # x
                               0.0,  0.1,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # y
                               0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # z
                               0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # roll
                               0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # pitch
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.1,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # yaw
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # vx
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # vy
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.04, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # vz
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,  # vroll
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  # vpitch
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.05, 0.0,  0.0,  0.0,  # vyaw
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  # ax
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  # ay
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.015] # az
                               
    # Initial estimate error covariance (P) - 초기 불확실성을 높여서 점프 방지
    initial_estimate_covariance: [1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # x
                                  0.0,  1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # y
                                  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                  0.0,  0.0,  0.0,  0.0,  0.0,  1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # yaw
                                  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.1,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # vx
                                  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.1,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # vy
                                  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,
                                  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,
                                  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.1,  0.0,  0.0,  0.0,  # vyaw
                                  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,
                                  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,
                                  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9]
    
    # 제어 입력 사용 (cmd_vel을 사용하여 예측 개선)
    use_control: true
    stamped_control: false
    control_config: [true, false, false, false, false, true]  # vx, vyaw만 사용
    control_timeout: 0.2
    
    # # 가속도 제한으로 급격한 변화 방지
    # acceleration_limits: [1.0, 0.0, 0.0, 0.0, 0.0, 3.0]
    # deceleration_limits: [1.0, 0.0, 0.0, 0.0, 0.0, 3.0]
    # acceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.9]
    # deceleration_gains: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
    
    # # 초기 상태 설정
    # initial_state: [0.0,  0.0,  0.0,
    #                 0.0,  0.0,  0.0,
    #                 0.0,  0.0,  0.0,
    #                 0.0,  0.0,  0.0,
    #                 0.0,  0.0,  0.0]
    
    # # 추가 안정화 옵션
    # dynamic_process_noise_covariance: false
    # permit_corrected_publication: false
    # publish_acceleration: false
    
    # 리셋 옵션
    # reset_on_time_jump: true
    
    # 출력 프레임 설정
    publish_filtered_odometry_message: true