ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.15
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom   # 로컬 오dom 추정

    predict_to_current_time: false  # 과도한 예측 방지
    print_diagnostics: true

    # ---------- RF2O: 위치만 신뢰 (x, y). yaw는 끈다 ----------
    odom0: /odom_rf2o
    odom0_config: [ true,  true,  false,   # x y z (z off)
                    false, false, true,   # roll pitch yaw (yaw off)
                    true, true, false,   # vx vy vz
                    false, false, false,   # vroll vpitch vyaw
                    true, true, true ]  # ax ay az
    odom0_differential: false
    odom0_relative:     false
    odom0_queue_size:   2
    odom0_nodelay:      true
    odom0_pose_rejection_threshold: 5.0

    # ---------- IMU: 각속도만 사용 (yaw 적분). 가속도는 끈다 ----------
    imu0: /imu   # 또는 /imu/data_raw (프레임/단위 확인)
    imu0_config: [ false, false, false,   # x y z
                   false, false, true,   # roll pitch yaw (orientation 안씀)
                   false, false, false,   # vx vy vz
                   true,  true,  true,    # vroll vpitch vyaw = angular velocity
                   false, false, false ]  # ax ay az (중력 문제로 off)
    imu0_differential: false
    imu0_relative:     false
    imu0_queue_size:   5
    imu0_nodelay:      true
    # imu0_remove_gravitational_acceleration: true  # orientation 없으면 효과 없음

    # # (선택) 공정잡음 약간: yaw를 과하게 흔들리지 않게
    # process_noise_covariance: [  0.05, 0,    0,    0,    0,    0,
    #                              0,    0.05, 0,    0,    0,    0,
    #                              0,    0,    0.1,  0,    0,    0,
    #                              0,    0,    0,    0.01, 0,    0,
    #                              0,    0,    0,    0,    0.01, 0,
    #                              0,    0,    0,    0,    0,    0.02,
    #                              0,0,0,0,0,0,  0.1,0,0, 0,0,0,  0,0,0 ]
    process_noise_covariance: [0.05, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.05, 0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.06, 0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.03, 0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.03, 0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.06, 0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.025, 0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.025, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.04, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.01, 0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.01, 0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.02, 0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.01, 0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.01, 0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.015]
